CREATE TABLE IF NOT EXISTS STUDENT (
  ROLL_NO TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE TEXT,
  AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'LARA', 'MUMBAI', '********', 14),
('2', 'KAI', 'TOKYO', '********', 12),
('3', 'ZARA', 'CAIRO', '********', 13),
('4', 'OMAR', 'DUBAI', '********', 14),
('5', 'NINA', 'PARIS', '********', 12);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 14 AND ADDRESS = 'MUMBAI';
SELECT * FROM STUDENT WHERE NAME LIKE 'Z%';
SELECT * FROM STUDENT WHERE AGE > 12;
SELECT * FROM STUDENT WHERE ROLL_NO IS NOT NULL;
